# Usamos la imagen oficial de Microsoft para Node 22
FROM mcr.microsoft.com/devcontainers/javascript-node:22-bookworm

# Activamos pnpm globalmente a través de corepack
RUN corepack enable && corepack prepare pnpm@latest --activate
